
#log.connection.level = debug
#log.default.level = info

loopback_users.guest = true
disk_free_limit.absolute = 1GB

# While testing, leave it accessible from any interface.
# In prod, for security, you can bind to localhost only
# and use iptables NATing to redirect restricted remote connections.

#listeners.tcp.local    = 127.0.0.1:5672
listeners.tcp.local    = 0.0.0.0:5672

management.tcp.port = 15672
#management.tcp.ip = 127.0.0.1
management.tcp.ip = 0.0.0.0

# Enable Prometheus-style metrics by default (https://github.com/docker-library/rabbitmq/issues/419)
# management_agent.disable_metrics_collector = true

load_definitions = /etc/rabbitmq/definitions.json
# Note: these definitions contains exchange, queues and bindings,
#       but also users, with dummy passwords. In production, please adjust!

