C4GH_PASSPHRASE=hello

OPTS=seckey=/etc/fega/seckey,passphrase_from_env=C4GH_PASSPHRASE,default_permissions,file_cache,dir_cache,supp_group=fega,username=runner,groupname=users,allow_other,fsname=FEGA
