PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS files (
    accession_id     text PRIMARY KEY,

    -- informative
    payload_size     bigint NOT NULL,
    payload_sha256   text NOT NULL CHECK (LENGTH(payload_sha256) = 64),
    plaintext_sha256 text NOT NULL CHECK (LENGTH(plaintext_sha256) = 64),
    inbox_sha256     text NOT NULL CHECK (LENGTH(inbox_sha256) = 64),

    -- auditing
    created_at     bigint NOT NULL DEFAULT (unixepoch('now'))
);

-- no need for AUTOINCREMENT
-- See: https://sqlite.org/autoinc.html#summary
CREATE TABLE IF NOT EXISTS jobs (

    id               integer PRIMARY KEY,

    correlation_id   text, -- info
    username         text NOT NULL,
    filepath         text NOT NULL,

    inbox_sha256     text, -- hex
    plaintext_sha256 text, -- hex

    accession_id     text,

    header           text, -- hex
    payload_sha256   text, -- hex
    payload_size     bigint, 

    -- staging_path     text   GENERATED ALWAYS AS (TRIM(username, '/') || '/' || LTRIM(filepath, '/')) VIRTUAL,

    status           text NOT NULL,
    error            text, -- in case of errors. NULL = no error

    -- auditing
    created_at     bigint NOT NULL DEFAULT (unixepoch('now')),
    edited_at      bigint NOT NULL DEFAULT (unixepoch('now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS jobs_idx ON jobs(username,filepath);

CREATE TABLE IF NOT EXISTS messages (
    id               integer PRIMARY KEY,

    correlation_id text NOT NULL,
    routing_key    text NOT NULL,
    message        text NOT NULL, -- already json formatted

    -- auditing
    created_at     bigint NOT NULL DEFAULT (unixepoch('now'))
);


-- We store session key sha256 hashes to avoid repetitions.
-- That way, it's likely that an encrypted payload was generated by a unique set of session keys
CREATE TABLE IF NOT EXISTS session_keys (

    sha256     text PRIMARY KEY,
    job_id     bigint, -- NULL = used in vault

    plaintext_sha256 text NOT NULL CHECK (LENGTH(plaintext_sha256) = 64),

    -- auditing
    created_at     bigint NOT NULL DEFAULT (unixepoch('now')),
    edited_at      bigint NOT NULL DEFAULT (unixepoch('now')),

    FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS on_sk_update AFTER UPDATE ON session_keys
BEGIN UPDATE session_keys SET edited_at = unixepoch('now') WHERE sha256 = NEW.sha256; END;

CREATE TRIGGER IF NOT EXISTS on_job_update AFTER UPDATE ON jobs
BEGIN UPDATE jobs SET edited_at = unixepoch('now') WHERE id = NEW.id; END;
