[DEFAULT]
logger = /etc/ega/logger.json

# 8 MB
bufsize = 8388608

# 64 MB
#bufsize = 67108864

[staging]
# %s will be the username
location = /ega/staging/%s

[vault]
location = /ega/vault

[backup]
location = /ega/backup

[broker]
connection = amqp://admin:secret@mq:5672/%2F

exchange = lega
queue = archive
qos = 10
