[api]
enabled = true  # for metrics/health checks

[sources.postgres]
type = "file"
include = ["$EGA_VAULT_DB_LOGS/*.log"]
ignore_checkpoints = true
read_from = "end"
ignore_older_secs = 86400
glob_minimum_cooldown_ms = 60000

multiline.start_pattern     = '^\[\d'
multiline.condition_pattern = '^\[\d'
multiline.mode = "halt_before"
multiline.timeout_ms = 5000


[transforms.pg]
type = "remap"
inputs = ["postgres"]
source = """
  parsed, err = parse_regex(.message,
                r'(?s)^\\[(?P<epoch_ms>.*)\\]\\[(?P<timestamp>.*) UTC\\]\\[(?P<pid>\\d+)\\]\\[(?P<lineno>\\d+)\\]\\[(?P<user>.*)\\]\\[(?P<database>.*)\\]<(?P<remote>.*)>\\s*(?P<pglevel>\\w+):\\s*(?P<message>.*)$')
  if err != null {
    log("PARSE ERROR: " + string!(.message), level: "error")
    abort
  }
  . = parsed
  .hostname = get_hostname!()
  .appname = "vault-db"
  .epoch_ms = to_int!(replace!(.epoch_ms, ".", "")) # Remove the dot (so x1000) and convert to integer
  ts = from_unix_timestamp!(.epoch_ms, "milliseconds")
  .@timestamp = format_timestamp!(value:ts, format: "%+", timezone: "UTC")
  .lineno = to_int!(.lineno) - 1
  .remote = if .remote == "" { "internal" } else { .remote }
  pglevel = string!(.pglevel)
  .levelname = if pglevel == "FATAL" {
    "CRITICAL"
  } else if pglevel == "ERROR" {
    "ERROR"
  } else if pglevel == "WARNING" {
    "WARNING"
  } else if pglevel == "LOG" {
    "INFO"
  } else if starts_with(pglevel, "DEBUG") {
    "DEBUG"
  } else {
    pglevel  # Fallback: keep original if unknown
  }
  del(.timestamp) 
  del(.pglevel)
"""
  
# in postgresql.conf, we use:
#      log_line_prefix = '[%n][%m][%p][%l][%u][%d]<%r> '
# where:
#     %n is a timestamp, including milliseconds
#     %t is a timestamp, without milliseconds
#     %p – Process ID
#     %u – username
#     %d – database name
#     %r – remote hostname, including port
#     %l – line number starting at 1
#     The message is <level>: <text>


[sinks.es]
type = "elasticsearch"
inputs = ["pg"]
endpoints = [ "http://elasticsearch:9200" ]
# tls.ca_file = "/etc/fega/es.cacert"
# tls.verify_certificate = true
# tls.verify_hostname = false # disabled for self-signed cert
bulk.index = "fega-vault-db"
bulk.max_actions = 1000  # Maximize bulk size to minimize callbacks
bulk.timeout_secs = 30   # Wait up to 30s to fill the bulk
request.rate_limit_duration_secs = 1
request.retry_attempts = 3
encoding.timestamp_format = "unix_ms"
mode = "bulk"
opensearch_service_type = "managed"

# [sinks.file_out]
# type = "file"
# inputs = ["pg"]
# #path = "/dev/stderr"
# path = "/proc/self/fd/2"
# encoding.codec = "json"
